import type { SportId } from "@/lib/sports";

/**
 * Dated moments the essay tells, in date order. Each text restates the essay's
 * own sentence(s) and cites the same sources (ids in lib/sources.ts); `at` is
 * the chapter or exhibit where the essay tells it. Chapter 11's timeline is
 * drawn from the entries marked `list: "reforms"`; a timeline page can use
 * the whole list.
 */
export type ScoreEvent = {
  id: string;
  /** As shown, e.g. "174 BC", "1820s", "2005–06". */
  year: string;
  /** For sorting: negative for BC. */
  sort: number;
  sport?: SportId;
  text: string;
  sources: string[];
  at: string;
  /** Same stamps as the essay's <Certainty>, where the essay uses one. */
  certainty?: "theory" | "disputed" | "story" | "unknown" | "proposal";
  list?: "reforms";
};

export const EVENTS: ScoreEvent[] = [
  {
    id: "eggs",
    year: "174 BC",
    sort: -174,
    sport: "chariot-racing",
    text: "Rome’s censors set up seven large eggs on the central barrier of the circus; one is taken down as each lap is completed.",
    sources: ["lacus-circus"],
    at: "ancient-scoreboards",
  },
  {
    id: "dolphins",
    year: "33 BC",
    sort: -33,
    sport: "chariot-racing",
    text: "Agrippa adds seven dolphins. Cassius Dio, writing more than two centuries later, says the officials kept losing count of the laps.",
    sources: ["lacus-circus", "spectacles-circus"],
    at: "ancient-scoreboards",
  },
  {
    id: "maya-stone",
    year: "c. 650–850 CE",
    sort: 650,
    sport: "ball-game",
    text: "A disc of volcanic rock from Maya territory, which the FIFA Museum presents as a scoreboard for the ballgame. How exactly it was used, nobody can say.",
    sources: ["fifa-meso"],
    at: "stone-disc",
  },
  {
    id: "cuju",
    year: "1187",
    sort: 1187,
    sport: "cuju",
    text: "Meng Yuanlao describes a cuju match at court: the winners were the side that sent the ball through a round opening in a net more often.",
    sources: ["fifa-cuju"],
    at: "ancient-scoreboards",
  },
  {
    id: "quarante-cinq",
    year: "1430s",
    sort: 1430,
    sport: "tennis",
    text: "A poem by Charles d’Orléans already plays on quarante-cinq, forty-five, as a tennis score.",
    sources: ["wiki-tennis-scoring", "time-tennis"],
    at: "prologue",
  },
  {
    id: "goldwin",
    year: "1706",
    sort: 1706,
    sport: "cricket",
    text: "William Goldwin’s Latin poem In Certamen Pilae, the oldest piece of cricket literature, has a scorer notching the total on a stick.",
    sources: ["antigone-goldwin"],
    at: "cut-in-the-stick",
  },
  {
    id: "play-for-love",
    year: "1740s",
    sort: 1740,
    sport: "tennis",
    text: "The phrase “to play for love”, meaning for nothing, turns up in card games. Dictionary makers lean towards it, rather than l’œuf, as the origin of tennis’s “love”.",
    sources: ["mw-love", "npr-love"],
    at: "prologue",
  },
  {
    id: "score-in-whist",
    year: "1742",
    sort: 1742,
    text: "“Score” is first recorded in English for the points made by players in a game, in whist.",
    sources: ["etym-score"],
    at: "word-history",
  },
  {
    id: "scorecards-1744",
    year: "1744",
    sort: 1744,
    sport: "cricket",
    text: "Two cricket scorecards survive from the summer: Slindon v London, and Kent v All England, the earliest known to record how batsmen were dismissed. The oldest surviving written code of the Laws of Cricket dates from the same year.",
    sources: ["wiki-1744", "earlycricket-slindon", "earlycricket-laws"],
    at: "match-becomes-data",
  },
  {
    id: "tie-1783",
    year: "1783",
    sort: 1783,
    sport: "cricket",
    text: "Hampshire and Kent are recorded as tied on 202 at Hambledon. The account that survives blames a long notch cut in the wrong place on the scorer’s stick.",
    sources: ["wiki-1783", "cricinfo-1783"],
    at: "cut-in-the-stick",
  },
  {
    id: "exchequer",
    year: "1820s",
    sort: 1820,
    text: "The English Exchequer stops keeping its accounts on split hazel tally sticks.",
    sources: ["smg-tally"],
    at: "cut-in-the-stick",
  },
  {
    id: "scoreboard-word",
    year: "1826",
    sort: 1826,
    text: "“Scoreboard” is first recorded, for a tavern blackboard of chalked debts; the sense of a display of a game follows in 1884.",
    sources: ["etym-scoreboard"],
    at: "word-history",
  },
  {
    id: "lords",
    year: "1846",
    sort: 1846,
    sport: "cricket",
    text: "Lord’s puts up a scoreboard.",
    sources: ["wisden-scoring"],
    at: "match-becomes-data",
  },
  {
    id: "lillywhite",
    year: "1848",
    sort: 1848,
    sport: "cricket",
    text: "Fred Lillywhite turns up at a match with a portable printing press, so spectators can buy a card updated to the fall of the latest wicket.",
    sources: ["wisden-scoring"],
    at: "match-becomes-data",
  },
  {
    id: "try-1890",
    year: "1890",
    sort: 1890,
    sport: "rugby",
    text: "When points are introduced, a try is worth a single point.",
    sources: ["wrm-points", "rugby365-scoring"],
    at: "rugby-chart",
  },
  {
    id: "try-1891",
    year: "1891",
    sort: 1891,
    sport: "rugby",
    text: "A try is worth two points.",
    sources: ["wrm-points", "rugby365-scoring"],
    at: "rugby-chart",
  },
  {
    id: "gaelic-goal-1892",
    year: "1892",
    sort: 1892,
    sport: "gaelic",
    text: "A goal is given a value for the first time: five points. Until then a goal outweighed any number of points.",
    sources: ["wiki-gaelic-scoring"],
    at: "notation-gaelic",
  },
  {
    id: "try-1893",
    year: "1893",
    sort: 1893,
    sport: "rugby",
    text: "A try is worth three points, where it stays for 78 years.",
    sources: ["wrm-points", "rugby365-scoring"],
    at: "rugby-chart",
  },
  {
    id: "gaelic-goal-1896",
    year: "1896",
    sort: 1896,
    sport: "gaelic",
    text: "The goal is cut to three points.",
    sources: ["wiki-gaelic-scoring"],
    at: "notation-gaelic",
  },
  {
    id: "davis-cup-1914",
    year: "1914",
    sort: 1914,
    sport: "tennis",
    text: "At the Davis Cup Challenge Round in Forest Hills, sets and games hang on a hand-changed board. It has no row for points.",
    sources: ["loc-davis-1914", "wiki-davis-1914"],
    at: "davis-cup-photo",
  },
  {
    id: "wrigley",
    year: "1937",
    sort: 1937,
    sport: "baseball",
    text: "Wrigley Field’s centre-field scoreboard is built under Bill Veeck. It is still operated by hand.",
    sources: ["mlb-wrigley", "wbez-wrigley"],
    at: "scoreboard-objects",
  },
  {
    id: "drop-goal-1948",
    year: "1948",
    sort: 1948,
    sport: "rugby",
    text: "The try, worth three, stops being worth less than a drop goal.",
    sources: ["wrm-points", "rugby365-scoring"],
    at: "rugby-chart",
  },
  {
    id: "pistons-lakers",
    year: "1950",
    sort: 1950,
    sport: "basketball",
    text: "The Fort Wayne Pistons beat the Minneapolis Lakers 19–18 by holding the ball: still the lowest-scoring game in NBA history.",
    sources: ["sportsmuseum-shotclock", "wbur-shotclock"],
    at: "clock-in-the-score",
  },
  {
    id: "shot-clock",
    year: "1954",
    sort: 1954,
    sport: "basketball",
    text: "Danny Biasone stages a scrimmage in Syracuse with a clock that gives the team in possession 24 seconds to shoot. The NBA adopts it that season.",
    sources: ["hmdb-shotclock", "lemoyne-shotclock"],
    at: "clock-in-the-score",
  },
  {
    id: "elo",
    year: "1960",
    sort: 1960,
    sport: "chess",
    text: "The United States Chess Federation adopts Arpad Elo’s rating system; FIDE follows in 1970.",
    sources: ["fide-elo"],
    at: "score-behind-the-score",
  },
  {
    id: "three-point-line",
    year: "1961",
    sort: 1961,
    sport: "basketball",
    text: "The three-point line begins, in the American Basketball League.",
    sources: ["hoopsgeek-3pt"],
    at: "score-designs-game",
  },
  {
    id: "tie-break-1970",
    year: "1970",
    sort: 1970,
    sport: "tennis",
    text: "A Grand Slam uses a tie-break at 6–6 for the first time, at the US Open: a nine-point, sudden-death version.",
    sources: ["usopen-tiebreak", "tennis-com-1970"],
    at: "reform-timeline",
    list: "reforms",
  },
  {
    id: "tie-break-1971",
    year: "1971",
    sort: 1971,
    sport: "tennis",
    text: "Wimbledon adopts a tie-break, at eight games all.",
    sources: ["wiki-tennis-scoring", "tennis-com-1970"],
    at: "reform-timeline",
    list: "reforms",
  },
  {
    id: "try-1971",
    year: "1971",
    sort: 1971,
    sport: "rugby",
    text: "A try rises to four points: now worth more than any kick.",
    sources: ["wrm-points", "rugby365-scoring"],
    at: "rugby-chart",
  },
  {
    id: "nba-three",
    year: "1979–80",
    sort: 1979,
    sport: "basketball",
    text: "The three-point line reaches the NBA. FIBA adopts it in 1984 and American college basketball in 1986.",
    sources: ["hoopsgeek-3pt"],
    at: "score-designs-game",
  },
  {
    id: "borg-mcenroe",
    year: "1980",
    sort: 1980,
    sport: "tennis",
    text: "McEnroe wins the fourth-set tie-break of the Wimbledon final 18–16. Borg wins the match anyway, 8–6 in a fifth set with no tie-break at all.",
    sources: ["wiki-1980-final", "tennis-com-1980"],
    at: "tie-break-film",
  },
  {
    id: "three-points-for-a-win",
    year: "1981",
    sort: 1981,
    sport: "football",
    text: "The English Football League gives three points for a win. The 1994 World Cup uses it, and FIFA formally adopts it in 1995.",
    sources: ["wiki-3pts", "tandf-3pts"],
    at: "score-designs-game",
  },
  {
    id: "score-bug",
    year: "1992",
    sort: 1992,
    sport: "football",
    text: "Sky Sports launches its Premier League coverage with the score and the match clock in the corner of the screen for the whole game.",
    sources: ["wiki-scorebug", "wiki-supersunday"],
    at: "score-on-television",
  },
  {
    id: "try-1992",
    year: "1992",
    sort: 1992,
    sport: "rugby",
    text: "A try rises to five points.",
    sources: ["wrm-points", "rugby365-scoring"],
    at: "rugby-chart",
  },
  {
    id: "fox-box",
    year: "1994",
    sort: 1994,
    sport: "american-football",
    text: "The “Fox Box” arrives with Fox’s first season of NFL coverage.",
    sources: ["forbes-foxbox"],
    at: "score-on-television",
  },
  {
    id: "rally-point",
    year: "1999",
    sort: 1999,
    sport: "volleyball",
    text: "Rally-point scoring replaces side-out scoring internationally; sets go from 15 to 25 points.",
    sources: ["fivb-game"],
    at: "reform-timeline",
    list: "reforms",
  },
  {
    id: "eleven-points",
    year: "2001",
    sort: 2001,
    sport: "table-tennis",
    text: "Games are cut from 21 points to 11.",
    sources: ["megaspin-11"],
    at: "reform-timeline",
    list: "reforms",
  },
  {
    id: "monument",
    year: "2005",
    sort: 2005,
    sport: "basketball",
    text: "Syracuse unveils a shot clock on a post as a monument.",
    sources: ["cny-shotclock-2026"],
    at: "shot-clock-monument",
  },
  {
    id: "shootout",
    year: "2005–06",
    sort: 2005.5,
    sport: "ice-hockey",
    text: "NHL regular-season games still level after overtime go to a shootout. The winners are given exactly one extra goal.",
    sources: ["nhl-rules"],
    at: "odd-nhl-shootout",
  },
  {
    id: "badminton-rally",
    year: "2006",
    sort: 2006,
    sport: "badminton",
    text: "21-point rally scoring replaces 15-point games in which only the server could score.",
    sources: ["badminton-asia"],
    at: "reform-timeline",
    list: "reforms",
  },
  {
    id: "four-point-shot",
    year: "2010",
    sort: 2010,
    sport: "basketball",
    text: "The Harlem Globetrotters introduce a four-point shot.",
    sources: ["globetrotters-4pt"],
    at: "score-designs-game",
  },
  {
    id: "isner-mahut",
    year: "2010",
    sort: 2010,
    sport: "tennis",
    text: "Isner and Mahut’s fifth set at Wimbledon finishes 70–68, in a first-round match that lasts 11 hours and 5 minutes over three days.",
    sources: ["wiki-isner-mahut"],
    at: "score-learns-to-stop",
  },
  {
    id: "expected-goals",
    year: "2012",
    sort: 2012,
    sport: "football",
    text: "Sam Green of the data company Opta publishes an influential explanation of expected goals.",
    sources: ["opta-xg"],
    at: "score-behind-the-score",
  },
  {
    id: "wimbledon-12-12",
    year: "2019",
    sort: 2019,
    sport: "tennis",
    text: "After Kevin Anderson’s 26–24 fifth set against Isner in 2018, Wimbledon introduces a final-set tie-break at 12–12.",
    sources: ["espn-wimbledon-2019"],
    at: "score-learns-to-stop",
  },
  {
    id: "ten-point-tie-break",
    year: "2022",
    sort: 2022,
    sport: "tennis",
    text: "All four Grand Slams settle a final set at 6–6 with the same 10-point tie-break.",
    sources: ["tennis-com-2022"],
    at: "reform-timeline",
    list: "reforms",
  },
  {
    id: "chichen-itza",
    year: "2023",
    sort: 2023,
    sport: "ball-game",
    text: "At Chichén Itzá, archaeologists find a limestone disc dated to 894 CE, carved with two ball players. Headlines call it a scoreboard; there is no evidence it kept score.",
    sources: ["mnd-chichen", "yucatan-scoreboard"],
    at: "ancient-scoreboards",
  },
  {
    id: "pba-four",
    year: "2024",
    sort: 2024,
    sport: "basketball",
    text: "The Philippine Basketball Association adopts a four-point arc 27 feet from the basket for official games.",
    sources: ["pba-4pt"],
    at: "score-designs-game",
  },
  {
    id: "gaelic-arc",
    year: "2025",
    sort: 2025,
    sport: "gaelic",
    text: "A 40-metre arc arrives: a score kicked over the bar from beyond it is worth two points, signalled with a new orange flag. In October a Special Congress makes the changes permanent.",
    sources: ["gaa-frc", "rte-congress"],
    at: "gaelic-arc",
  },
  {
    id: "quadball-proposal",
    year: "2026",
    sort: 2026,
    sport: "quadball",
    text: "The International Quadball Association asks its community about making a goal worth 1 and the flag catch 3. The change does not make it into the 2026 rulebook.",
    sources: ["iqa-consult", "iqa-2026"],
    at: "scoreboard-changes-rules",
    certainty: "proposal",
  },
  {
    id: "monument-moves",
    year: "2026",
    sort: 2026.3,
    sport: "basketball",
    text: "The Syracuse shot clock monument moves to the entrance of the Museum of Science and Technology.",
    sources: ["cny-shotclock-2026"],
    at: "shot-clock-monument",
  },
];
