/** Every sport (or contest) the essay shows or discusses, with its display name. */
export const SPORTS = {
  tennis: "Tennis",
  cricket: "Cricket",
  baseball: "Baseball",
  basketball: "Basketball",
  football: "Football",
  "american-football": "American football",
  rugby: "Rugby union",
  gaelic: "Gaelic football",
  afl: "Australian football",
  golf: "Golf",
  darts: "Darts",
  bowling: "Tenpin bowling",
  volleyball: "Volleyball",
  "table-tennis": "Table tennis",
  badminton: "Badminton",
  korfball: "Korfball",
  athletics: "Athletics",
  wrestling: "Wrestling",
  "chariot-racing": "Chariot racing",
  "ball-game": "Mesoamerican ballgame",
  "speed-skating": "Speed skating",
  "nordic-combined": "Nordic combined",
  "ice-hockey": "Ice hockey",
  pickleball: "Pickleball",
  cornhole: "Cornhole",
  shuffleboard: "Shuffleboard",
  sailing: "Sailing",
  "roller-derby": "Roller derby",
  kabaddi: "Kabaddi",
  curling: "Curling",
  quadball: "Quadball",
  chess: "Chess",
  cuju: "Cuju",
} as const;

export type SportId = keyof typeof SPORTS;
